### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by sserghei** [TeeSeal/saltedge_task#1]
Add methods :connect, fetch, disconnect.
Add class Account.

```
data = {
      date:        'td[1]',
      time:        'td[2]',
      type:        'td[3]',
      description: 'td[4]',
      amount:      'td[5]',
      currency:    'td[6]'
    }
```
I don't understand what td means???!!

Transaction should have currency_code field, amount should be float, date should be in json format:"2012-12-12"

**Comment by TeeSeal** [comment]
>Add methods :connect, fetch, disconnect.
Done.

>Add class Account.
Done.

>I don't understand what td means???!!
https://www.w3schools.com/tags/tag_td.asp

This is what the table cells look like on the page:
```
<td align="left" style="width:30%;">
  <span id="aspx_accountinformation_accountsummary_ascxbd7b4b16-9cae-4790-8e8f-b0cf3f875fbb_DebitCardAccountHistoryPopup_gridDebitCardTransactionHistory_lblCurrency_0">ATM MAIB UTM&gt;CHISINAU                 MD</span>
</td>
```
The span id is randomly generated on each logon and the label at the end is missleading:
`lblCurrency` -> ATM MAIB UTM... (which is description, not currency)
That's why I decided just to select the table cells by their index.

>Transaction should have currency_code field, amount should be float, date should be in json format:"2012-12-12"

This is what they look like now:
```
        {
          "date": "2017-01-18T12:22:48+02:00",
          "type": "Cash",
          "description": "ATM MAIB UTM>CHISINAU                 MD",
          "amount": -100.0,
          "currency": "MDL"
        }
```
That's what JSON generated from the DateTime object itself.

If anything else needs changing, please let me know.
